---
# Directories
temporary_directory: "/tmp"
volume_directory: "/tmp"

# Domain
domain_name: example.local

# Docker
docker_network_name: "proxy_network"

# Docker image versions
traefik_version: v1.7.20

# Traefik configuration
traefik_user: admin
traefik_email_address: "admin@domain.com"

# SSL certs
is_using_local_ssl_certs: '{{ (domain_name | regex_search("^((?!\.com).)*$")) == domain_name }}'
is_using_acme_staging: '{{ domain_name != "example.com" }}'

# Traefik configurations
is_traefik_metrics_enabled: true
is_traefik_tracing_enabled: true